"""Emit the Option-B Phase O-2 curated factorial into `configs/option_b/`.

12 configs = 3 circuits (span the accuracy↔variance frontier) × 4
regularization regimes. Each is a 3-seed proxy at the locked h=3
evaluation protocol. The `option_b` meta-block records the circuit /
regime / knob values so `scripts/summarize_option_b.py` can build the
penalized-objective ranking table.

The hypothesis under test: regularization collapses an expressive
circuit's seed variance under the G2 gate (σ ≤ 0.00831) WITHOUT
surrendering its accuracy gain — i.e. the accuracy/variance tradeoff is a
regularization-strength artifact, not a fundamental ansatz property.

Re-running is safe: deterministic overwrite.

Usage:
    python scripts/generate_option_b_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT = REPO_ROOT / "configs" / "option_b"
OUT.mkdir(parents=True, exist_ok=True)

PROXY_SEEDS = [0, 1, 2]            # 3-seed proxy — minimum to estimate σ
G2_SIGMA_GATE = 0.00831           # 0.5 · σ_classical_H4 (from baseline_lock)

# --- The 3 circuits spanning the frontier --------------------------------
CIRCUITS = {
    "se_6q3l": {  # accuracy-strong, variance-broken — needs the G2 fix
        "ansatz": {"name": "strongly_entangling", "params": {"encoding": "rx"}},
        "num_qubits": 6, "num_layers": 3,
    },
    "dr_4q3l": {  # variance-strong, accuracy-short — the reference topology
        "ansatz": {"name": "data_reuploading",
                   "params": {"entanglement": "ring", "encoding": "rx"}},
        "num_qubits": 4, "num_layers": 3,
    },
    "he_4q3l": {  # middle of the frontier
        "ansatz": {"name": "hardware_efficient",
                   "params": {"entanglement": "ring", "encoding": "rx"}},
        "num_qubits": 4, "num_layers": 3,
    },
}

# --- The 4 regularization regimes ----------------------------------------
# Each regime is a delta on top of the R0 control. Keys map onto
# model.* / training.* / physics.* fields the trainer already honors.
REGIMES = {
    "R0_control": {
        "weight_decay": 0.0, "lr": 0.002, "lr_schedule": "constant",
        "grad_clip_norm": 1.0, "init_circuit_std": 0.05,
        "lambda_logistic": 0.0,
    },
    "R1_weight_decay": {
        "weight_decay": 0.001, "lr": 0.002, "lr_schedule": "constant",
        "grad_clip_norm": 1.0, "init_circuit_std": 0.05,
        "lambda_logistic": 0.0,
    },
    "R2_physics_prior": {
        "weight_decay": 0.0, "lr": 0.002, "lr_schedule": "constant",
        "grad_clip_norm": 1.0, "init_circuit_std": 0.05,
        "lambda_logistic": 0.1,
    },
    "R3_smooth_convergence": {
        "weight_decay": 0.0, "lr": 0.002, "lr_schedule": "cosine",
        "grad_clip_norm": 0.5, "init_circuit_std": 0.02,
        "lambda_logistic": 0.0,
    },
}


def _config(circuit_key: str, regime_key: str) -> dict:
    c = CIRCUITS[circuit_key]
    r = REGIMES[regime_key]
    return {
        "option_b": {
            "circuit": circuit_key,
            "regime": regime_key,
            "proxy_seeds": len(PROXY_SEEDS),
            "g2_sigma_gate": G2_SIGMA_GATE,
            "knobs": dict(r),
        },
        "data": {
            "csv_path": "data/raw/qZETA_data_copy.csv",
            "feature_cols": ["OD", "PRE", "TEMP_EXT", "TEMP_CULTURE",
                             "PAR_LIGHT", "PH", "DO"],
            "target_col": "OD",
            "od_min": 0.0, "od_max": None, "od_phys_max": 3.8,
        },
        "windows": {
            "window_size": 24, "stride": 1,
            "horizon_hours": 3.0, "horizon_tol_hours": 0.0835,
        },
        "split": {"train_ratio": 0.70, "val_ratio": 0.15},
        "model": {
            "ansatz": c["ansatz"],
            "num_qubits": c["num_qubits"],
            "num_layers": c["num_layers"],
            "delta_scale": 0.1,
            "tau_min": 0.1,
            "tau_init": 1.0,
            "init_head_std": 0.1,
            "init_circuit_std": r["init_circuit_std"],
            "solver": "tsit5",
            "rtol": 0.001, "atol": 0.0001, "dt0": 0.05,
            "max_steps": 12288,
        },
        "training": {
            "epochs": 60, "batch_size": 32,
            "lr": r["lr"],
            "weight_decay": r["weight_decay"],
            "eval_every": 5, "patience": 6,
            "grad_clip_norm": r["grad_clip_norm"],
            "lr_schedule": r["lr_schedule"],
        },
        "physics": {
            "lambda_logistic": r["lambda_logistic"],
            "mu_norm": 0.4, "K_norm": 1.0,
        },
        "seeds": list(PROXY_SEEDS),
    }


HEADER = (
    "# Auto-generated by scripts/generate_option_b_configs.py.\n"
    "# Do not edit by hand — change the generator and re-run.\n"
    "# Option-B Phase O-2: curated factorial (circuit × regularization regime),\n"
    "# 3-seed proxy at the locked h=3 protocol.\n"
)


def main() -> None:
    n = 0
    for ck in CIRCUITS:
        for rk in REGIMES:
            cfg = _config(ck, rk)
            path = OUT / f"{ck}__{rk}.yaml"
            path.write_text(HEADER + yaml.safe_dump(cfg, sort_keys=False))
            print(f"wrote {path}")
            n += 1
    print(f"\n{n} configs written to {OUT}/")


if __name__ == "__main__":
    main()
