"""Emit configs/synthetic_ode/*.yaml — 5 ODE systems × {classical, QLNN}.

Mirrors the LOCKED bioreactor protocol exactly (window=24, stride=1,
h=3, 70/15/15 chronological, 5 seeds, matched params: classical
hidden_size=4 ≈ QLNN data_reuploading 4q/3L) so synthetic-ODE results
are head-to-head comparable with the qZETA study and the Option-B gate
machinery transfers unchanged.

Synthetic specifics:
  - feature_cols / target_col read from data/synthetic/manifest.json
  - od_min/od_max/od_phys_max all null: train-only MinMax, NO prediction
    clipping (ODE states are signed — Lorenz x, FHN v, Kuramoto phases —
    so the qZETA [0, 3.8] physical clip would be actively wrong).

Run scripts/generate_synthetic_ode_data.py first (writes the manifest).

Usage:
    python scripts/generate_synthetic_ode_configs.py
"""
from __future__ import annotations

import json
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "data" / "synthetic" / "manifest.json"
OUT = REPO_ROOT / "configs" / "synthetic_ode"


def _common_data(info: dict) -> dict:
    return {
        "csv_path": info["csv"],
        "feature_cols": info["feature_cols"],
        "target_col": info["target_col"],
        "od_min": None,
        "od_max": None,
        "od_phys_max": None,   # no physical clip — ODE states are signed
    }


def _windows() -> dict:
    return {"window_size": 24, "stride": 1,
            "horizon_hours": 3.0, "horizon_tol_hours": 0.0835}


def _split() -> dict:
    return {"train_ratio": 0.70, "val_ratio": 0.15}


def _classical_cfg(info: dict) -> dict:
    return {
        "data": _common_data(info),
        "windows": _windows(),
        "split": _split(),
        "model": {  # ~90 params — the matched comparator
            "hidden_size": 4, "tau_min": 0.1, "forecast_steps": 4,
            "delta_scale": 0.1, "ode_method": "euler",
        },
        "training": {
            "epochs": 300, "batch_size": 64, "lr": 0.002,
            "weight_decay": 0.0, "eval_every": 10, "patience": 10,
            "grad_clip_norm": 1.0,
        },
        "physics": {"lambda_logistic": 0.0},
        "seeds": [0, 1, 2, 3, 4],
    }


def _qlnn_cfg(info: dict) -> dict:
    return {
        "data": _common_data(info),
        "windows": _windows(),
        "split": _split(),
        "model": {
            "ansatz": {"name": "data_reuploading",
                       "params": {"entanglement": "ring", "encoding": "rx"}},
            "num_qubits": 4, "num_layers": 3,
            "delta_scale": 0.1, "tau_min": 0.1, "tau_init": 1.0,
            "init_head_std": 0.1, "init_circuit_std": 0.05,
            "solver": "tsit5", "rtol": 0.001, "atol": 0.0001,
            "dt0": 0.05, "max_steps": 12288,
        },
        "training": {
            "epochs": 60, "batch_size": 32, "lr": 0.002,
            "weight_decay": 0.0, "eval_every": 5, "patience": 6,
            "grad_clip_norm": 1.0, "lr_schedule": "constant",
        },
        "physics": {"lambda_logistic": 0.0, "mu_norm": 0.4, "K_norm": 1.0},
        "seeds": [0, 1, 2, 3, 4],
    }


HEADER = (
    "# Auto-generated by scripts/generate_synthetic_ode_configs.py.\n"
    "# Synthetic ODE benchmark — LOCKED bioreactor protocol "
    "(window=24, h=3, 70/15/15, 5 seeds).\n"
    "# Mirrors qZETA methodology so results are head-to-head comparable.\n"
)


def main() -> None:
    if not MANIFEST.exists():
        raise SystemExit(
            f"missing {MANIFEST} — run scripts/generate_synthetic_ode_data.py")
    manifest = json.loads(MANIFEST.read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    n = 0
    for name, info in manifest.items():
        for stack, builder in (("classical", _classical_cfg),
                               ("qlnn", _qlnn_cfg)):
            cfg = builder(info)
            path = OUT / f"{name}__{stack}.yaml"
            path.write_text(HEADER + yaml.safe_dump(cfg, sort_keys=False))
            print(f"wrote {path}")
            n += 1
    print(f"\n{n} configs ({len(manifest)} systems × 2 stacks) → {OUT}/")


if __name__ == "__main__":
    main()
