"""Emit the per-axis ablation YAMLs into `configs/circuit_search/`.

This is a one-shot generator — the YAMLs it produces are the actual files
fed to `train_qlnn.py` by `run_circuit_search.sh`. The reason to keep this
generator (rather than committing 13 hand-edited YAMLs and walking away):

  * Single source of truth for the search-grid axes — if you want to add a
    new entanglement level or a 5th depth, you edit ONE dict here.
  * The `circuit_search` meta-block inside each YAML is what
    `summarize_circuit_search.py` keys on for the per-axis effect plots —
    it has to be consistent across all configs. A generator guarantees that.
  * Re-running this is safe: it overwrites the YAMLs deterministically.

The reference cell (4 qubits, 3 layers, data_reuploading, ring, RX) is the
*shared* config that every axis sweep falls through. It is intentionally
identical to `configs/qlnn_hybrid.yaml` (modulo horizon=3.0) so the
existing `results/qlnn_hybrid_h3/` headline run can be reused as the
reference data point — no need to re-train it.

Usage:
    python scripts/generate_circuit_search_configs.py
"""
from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT = REPO_ROOT / "configs" / "circuit_search"
OUT.mkdir(parents=True, exist_ok=True)


# Reference cell shared by every axis-sweep.
REFERENCE: dict[str, Any] = {
    "ansatz_name": "data_reuploading",
    "num_qubits": 4,
    "num_layers": 3,
    "ansatz_params": {"entanglement": "ring", "encoding": "rx"},
}


def _yaml_str(d: dict[str, Any], indent: int = 0) -> str:
    """Tiny dict→YAML emitter (good enough for our shape). Avoids importing
    PyYAML at generator time."""
    pad = " " * indent
    out = []
    for k, v in d.items():
        if isinstance(v, dict):
            out.append(f"{pad}{k}:")
            out.append(_yaml_str(v, indent + 2))
        elif isinstance(v, bool):
            out.append(f"{pad}{k}: {'true' if v else 'false'}")
        elif isinstance(v, (int, float)):
            out.append(f"{pad}{k}: {v}")
        elif v is None:
            out.append(f"{pad}{k}: null")
        else:
            out.append(f"{pad}{k}: {v}")
    return "\n".join(out)


HEADER = """\
# Auto-generated by scripts/generate_circuit_search_configs.py.
# Do not edit by hand — change the generator and re-run.
#
# This config samples ONE point in the per-axis circuit-search ablation
# defined in the plan-of-record. The `circuit_search` meta-block tells
# `scripts/summarize_circuit_search.py` which axis/level this is.
#
# Eval protocol = locked h=3 (matches results/qlnn_hybrid_h3/).
# Single seed for the proxy budget; promote to 5 seeds via Phase 4.
"""


def emit(
    *,
    filename: str,
    axis: str,
    level: str,
    is_reference: bool,
    ansatz_name: str,
    num_qubits: int,
    num_layers: int,
    ansatz_params: dict[str, Any],
) -> None:
    body = {
        "circuit_search": {
            "axis": axis,
            "level": level,
            "is_reference": is_reference,
        },
        "data": {
            "csv_path": "data/raw/qZETA_data_copy.csv",
            "feature_cols": "[OD, PRE, TEMP_EXT, TEMP_CULTURE, PAR_LIGHT, PH, DO]",
            "target_col": "OD",
            "od_min": 0.0,
            "od_max": "null",
            "od_phys_max": 3.8,
        },
        "windows": {
            "window_size": 24,
            "stride": 1,
            "horizon_hours": 3.0,
            "horizon_tol_hours": 0.0835,
        },
        "split": {"train_ratio": 0.70, "val_ratio": 0.15},
        "model": {
            "num_qubits": num_qubits,
            "num_layers": num_layers,
            "delta_scale": 0.1,
            "tau_min": 0.1,
            "tau_init": 1.0,
            "init_head_std": 0.1,
            "solver": "tsit5",
            "rtol": 0.001,
            "atol": 0.0001,
            "dt0": 0.05,
            "max_steps": 12288,
        },
        "training": {
            "epochs": 60,
            "batch_size": 32,
            "lr": 0.002,
            "weight_decay": 0.0,
            "eval_every": 5,
            "patience": 6,
            "grad_clip_norm": 1.0,
        },
        "physics": {"lambda_logistic": 0.0, "mu_norm": 0.4, "K_norm": 1.0},
        "seeds": "[0]",
    }
    text = HEADER + "\n" + _yaml_str(body)
    # The ansatz block goes inside `model` (PyYAML would write nested fine but
    # we inline it manually so the file ordering reads top-down by section).
    ansatz_text = "  ansatz:\n"
    ansatz_text += f"    name: {ansatz_name}\n"
    if ansatz_params:
        ansatz_text += "    params:\n"
        for k, v in ansatz_params.items():
            if isinstance(v, bool):
                ansatz_text += f"      {k}: {'true' if v else 'false'}\n"
            else:
                ansatz_text += f"      {k}: {v}\n"
    text = text.replace(
        "model:\n  num_qubits:",
        "model:\n" + ansatz_text + "  num_qubits:",
    )
    (OUT / filename).write_text(text + "\n")
    print(f"wrote {OUT / filename}")


def _cell(**overrides: Any) -> dict[str, Any]:
    """Reference cell with selected overrides."""
    out = {
        "ansatz_name": REFERENCE["ansatz_name"],
        "num_qubits": REFERENCE["num_qubits"],
        "num_layers": REFERENCE["num_layers"],
        "ansatz_params": dict(REFERENCE["ansatz_params"]),
    }
    if "ansatz_params" in overrides:
        out["ansatz_params"] = {**out["ansatz_params"], **overrides.pop("ansatz_params")}
    out.update(overrides)
    return out


def main() -> None:
    # 0. Reference cell — shared starting point.
    emit(
        filename="reference.yaml",
        axis="reference", level="data_reuploading_4q3L_ring_rx",
        is_reference=True,
        **_cell(),
    )

    # 1. Entanglement axis (linear / ring=ref / all_to_all).
    emit(filename="entanglement_linear.yaml",
         axis="entanglement", level="linear", is_reference=False,
         **_cell(ansatz_params={"entanglement": "linear"}))
    emit(filename="entanglement_all_to_all.yaml",
         axis="entanglement", level="all_to_all", is_reference=False,
         **_cell(ansatz_params={"entanglement": "all_to_all"}))

    # 2. Variational gate axis. Swap the whole ansatz family for these.
    emit(filename="variational_hardware_efficient_ry_rz.yaml",
         axis="variational", level="ry_rz_hardware_efficient", is_reference=False,
         ansatz_name="hardware_efficient",
         num_qubits=REFERENCE["num_qubits"], num_layers=REFERENCE["num_layers"],
         ansatz_params={"entanglement": "ring", "encoding": "rx"})
    emit(filename="variational_strongly_entangling.yaml",
         axis="variational", level="rot_strongly_entangling", is_reference=False,
         ansatz_name="strongly_entangling",
         num_qubits=REFERENCE["num_qubits"], num_layers=REFERENCE["num_layers"],
         ansatz_params={"encoding": "rx"})

    # 3. Encoding axis (RX=ref, RY). IQP-style left out of v1 because it
    # needs a different shape contract; revisit in Phase 4.
    emit(filename="encoding_ry.yaml",
         axis="encoding", level="ry", is_reference=False,
         **_cell(ansatz_params={"encoding": "ry"}))

    # 4. Depth axis (1, 2, 3=ref, 5).
    for d in (1, 2, 5):
        emit(filename=f"depth_{d}.yaml",
             axis="depth", level=f"L{d}", is_reference=False,
             **_cell(num_layers=d))

    # 5. Qubits axis (2, 4=ref, 6).
    for q in (2, 6):
        emit(filename=f"qubits_{q}.yaml",
             axis="qubits", level=f"Q{q}", is_reference=False,
             **_cell(num_qubits=q))

    # 6. Ansatz-family axis (data_reuploading=ref + hardware_efficient + brickwall
    # all at default 4q/3L/ring/RX). This duplicates `variational_*` for the
    # *family* effect — gives a clean "ansatz family" axis in the figure.
    emit(filename="ansatz_brickwall.yaml",
         axis="ansatz_family", level="brickwall", is_reference=False,
         ansatz_name="brickwall",
         num_qubits=REFERENCE["num_qubits"], num_layers=REFERENCE["num_layers"],
         ansatz_params={"encoding": "rx", "reupload": False})


if __name__ == "__main__":
    main()
